import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={`min-h-dvh relative bg-cream`}>
        <div className="w-full h-full absolute">
          <Header />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
