import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: "/logo/web-logo.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className="min-h-dvh relative bg-gradient-to-b from-accent via-cream/70 to-cream">
        <div className="absolute h-full w-full">
          <Header />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
